### ISSUE TITLE
Betterstack didn't receive part of logs from Jobs

### ISSUE THREAD

**Issue by svyatoslavpavlov** [logtail/monolog-logtail#20]
Logs from Jobs mostly didn't achieve betterstack
logtail/monolog-logtail v2.1.0
laravel 9

Simple example below
```
...
  'logtail' => [
            'driver' => 'monolog',
            'level' => env('LOG_LEVEL', 'debug'),
            'handler' => LogtailHandler::class,
            'with' => [
                'sourceToken' => env('LOG_SECURE_TOKEN', 'debug'),
            ],
        ],
...
```
```

class TesJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        Log::debug("test");
    }
}

```

```
...

        for ($i = 0; $i < 100; $i++) {
            TesJob::dispatch();
        }
...
```

**Comment by curusarn** [comment]
Hi @svyatoslavpavlov,

Thank you for reporting this. I'm passing it to the team to take a look right away.
I'll keep you updated here on GitHub.

Thanks again for reaching out!

**Comment by gyfis** [comment]
Hey @svyatoslavpavlov, the issue you saw should be fixed now. Let us know if there's anything else, please!

Closing the issue.

**Comment by jmadlena** [comment]
@gyfis @curusarn Sorry to revive a closed issue, but I am still seeing this randomly in Laravel v11.41.3 during jobs.

I will randomly get an error in my error tracker saying `Failed to send 3 log records to Better Stack because of RuntimeException: Curl error (code 16)`. It's usually 3 log records, but the number can vary.

This doesn't happen every time, but it is very frequent and it's really polluting my error tracker.

I've tried to look into what Curl error 16 could mean, but it's a very generic error:

```
CURLE_HTTP2 (16)

A problem was detected in the HTTP2 framing layer. This is somewhat generic and can be one out of several problems, see the error buffer for details.
```

It's being thrown at line 90 at the `handleBatch` function in `/src/Monolog/SynchronousLogtailHandler.php`:

`trigger_error("Failed to send " . count($records) . " log records to Better Stack because of " . $throwable, E_USER_WARNING);`

Since it's not a throwable, I can't look into the error buffer, as mention in the Curl docs.

From my server I can ping `in.logs.betterstack.com` without issue, so I'm not sure if this is some transient network issue, or something at the library/server level.

Here's my app's details:

PHP: 8.2
Laravel: 11.41.3
Package version: 3.3.0

Any troubleshooting tips or help would be greatly appreciated! I really want to stay with BetterStack logs, but won't be able to unless I can fix this.
